openapi: "3.0.0"
info:
  title: Redocly Museum API
  description: >-
    An imaginary, but delightful Museum API for interacting with museum services
    and information. Built with love by Redocly.
  version: 1.0.0
  contact:
    email: team@redocly.com
    url: https://redocly.com/docs/cli/
  x-logo:
    url: https://redocly.github.io/redoc/museum-logo.png
    altText: Museum logo
  license:
    name: MIT
    url: 'https://opensource.org/license/mit/ '
servers:
  - url: https://api.fake-museum-example.com/v1
paths:
  /museum-hours:
    $ref: paths/museum-hours.yaml
  /special-events:
    $ref: paths/special-events.yaml
  /special-events/{eventId}:
    $ref: paths/special-events_{eventId}.yaml
  /tickets:
    $ref: paths/tickets.yaml
  /tickets/{ticketId}/qr:
    $ref: paths/tickets_{ticketId}_qr.yaml
components:
  securitySchemes:
    MuseumPlaceholderAuth:
      type: http
      scheme: basic
tags:
  - name: Operations
    x-displayName: About the museum
    description: Operational information about the museum.
  - name: Events
    x-displayName: Upcoming events
    description: Special events hosted by the Museum.
  - name: Tickets
    x-displayName: Buy tickets
    description: Museum tickets for general entrance or special events.
x-tagGroups:
  - name: Plan your visit
    tags:
      - Operations
      - Events
  - name: Purchases
    tags:
      - Tickets
security:
  - MuseumPlaceholderAuth: []
