# https://blog.stackademic.com/fully-typed-web-apps-with-openapi-part-1-595d55766670
# generate-api:petstore": "openapi-generator-cli generate -i ./src/api/petstore/api.yaml -g typescript-axios -o ./src/api/petstore/ --skip-validate-spec --additional-properties=useSingleRequestParameter=true,withoutPrefixEnums=true,enumNameSuffix=,withSeparateModelsAndApi=true,apiPackage=server,modelPackage=model --openapi-normalizer REFACTOR_ALLOF_WITH_PROPERTIES_ONLY=true
axiosVersion: 1.7.4
useSingleRequestParameter: true
withoutPrefixEnums: true
enumNameSuffix: ""
withSeparateModelsAndApi: true
apiPackage: server
modelPackage: model
