// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Redocly Museum API
 *
 * An imaginary, but delightful Museum API for interacting with museum services and information. Built with love by Redocly.
 *
 * API version: 1.0.0
 * Contact: team@redocly.com
 */

package api

import (
	"context"
	"net/http"
	"errors"
)

// OperationsAPIService is a service that implements the logic for the OperationsAPIServicer
// This service should implement the business logic for every endpoint for the OperationsAPI API.
// Include any external packages or services that will be required by this service.
type OperationsAPIService struct {
}

// NewOperationsAPIService creates a default api service
func NewOperationsAPIService() *OperationsAPIService {
	return &OperationsAPIService{}
}

// GetMuseumHours - Get museum hours
func (s *OperationsAPIService) GetMuseumHours(ctx context.Context, startDate string, page int32, limit int32) (ImplResponse, error) {
	// TODO - update GetMuseumHours with the required logic for this service method.
	// Add api_operations_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response Response(200, []MuseumDailyHours{}) or use other options such as http.Ok ...
	// return Response(200, []MuseumDailyHours{}), nil

	// TODO: Uncomment the next line to return response Response(400, {}) or use other options such as http.Ok ...
	// return Response(400, nil),nil

	// TODO: Uncomment the next line to return response Response(404, {}) or use other options such as http.Ok ...
	// return Response(404, nil),nil

	return Response(http.StatusNotImplemented, nil), errors.New("GetMuseumHours method not implemented")
}
