/* tslint:disable */
/* eslint-disable */
/**
 * Redocly Museum API
 * An imaginary, but delightful Museum API for interacting with museum services and information. Built with love by Redocly.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: team@redocly.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { TicketType } from './ticket-type';

/**
 * Details for a museum ticket after a successful purchase.
 * @export
 * @interface BuyMuseumTicketsResponse
 */
export interface BuyMuseumTicketsResponse {
    /**
     * Confirmation message after a ticket purchase.
     * @type {string}
     * @memberof BuyMuseumTicketsResponse
     */
    'message': string;
    /**
     * Name of the special event
     * @type {string}
     * @memberof BuyMuseumTicketsResponse
     */
    'eventName'?: string;
    /**
     * Unique identifier for museum ticket. Generated when purchased.
     * @type {string}
     * @memberof BuyMuseumTicketsResponse
     */
    'ticketId': string;
    /**
     * 
     * @type {TicketType}
     * @memberof BuyMuseumTicketsResponse
     */
    'ticketType': TicketType;
    /**
     * 
     * @type {string}
     * @memberof BuyMuseumTicketsResponse
     */
    'ticketDate': string;
    /**
     * Unique confirmation code used to verify ticket purchase.
     * @type {string}
     * @memberof BuyMuseumTicketsResponse
     */
    'confirmationCode': string;
}



