/* tslint:disable */
/* eslint-disable */
/**
 * Redocly Museum API
 * An imaginary, but delightful Museum API for interacting with museum services and information. Built with love by Redocly.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: team@redocly.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Daily operating hours for the museum.
 * @export
 * @interface MuseumDailyHours
 */
export interface MuseumDailyHours {
    /**
     * 
     * @type {string}
     * @memberof MuseumDailyHours
     */
    'date': string;
    /**
     * Time the museum opens on a specific date. Uses 24 hour time format (`HH:mm`).
     * @type {string}
     * @memberof MuseumDailyHours
     */
    'timeOpen': string;
    /**
     * Time the museum closes on a specific date. Uses 24 hour time format (`HH:mm`).
     * @type {string}
     * @memberof MuseumDailyHours
     */
    'timeClose': string;
}

