/* tslint:disable */
/* eslint-disable */
/**
 * Redocly Museum API
 * An imaginary, but delightful Museum API for interacting with museum services and information. Built with love by Redocly.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: team@redocly.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Information about a special event.
 * @export
 * @interface SpecialEventResponse
 */
export interface SpecialEventResponse {
    /**
     * Identifier for a special event.
     * @type {string}
     * @memberof SpecialEventResponse
     */
    'eventId': string;
    /**
     * Name of the special event
     * @type {string}
     * @memberof SpecialEventResponse
     */
    'name': string;
    /**
     * Location where the special event is held
     * @type {string}
     * @memberof SpecialEventResponse
     */
    'location': string;
    /**
     * Description of the special event
     * @type {string}
     * @memberof SpecialEventResponse
     */
    'eventDescription': string;
    /**
     * List of planned dates for the special event
     * @type {Array<string>}
     * @memberof SpecialEventResponse
     */
    'dates': Array<string>;
    /**
     * Price of a ticket for the special event
     * @type {number}
     * @memberof SpecialEventResponse
     */
    'price': number;
}

