/* tslint:disable */
/* eslint-disable */
/**
 * Redocly Museum API
 * An imaginary, but delightful Museum API for interacting with museum services and information. Built with love by Redocly.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: team@redocly.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Type of ticket being purchased. Use `general` for regular museum entry and `event` for tickets to special events.
 * @export
 * @enum {string}
 */

export const TicketType = {
    Event: 'event',
    General: 'general'
} as const;

export type TicketType = typeof TicketType[keyof typeof TicketType];



